version: "3.4"
# author: movrment
services:
    web:
        image: tomcat:8.5.51-jdk8
        volumes:
                - ./isolate/:/usr/local/tomcat/webapps/ROOT/:ro
                - ./flag.txt:/flag:ro
                # made life a bit easier 
                # - /dev/null:/etc/resolv.conf:ro
        user: 1000:1000
        ports:
                - '8009:8080'
        environment:
                - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom
        networks:
                - privateisolate
    nginx:
        image: nginx:1.21.3
        volumes:
                - ./nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
                - privateisolate
                - public
        ports:
                - '8010:8080'

networks:
        privateisolate:
                internal: true
        public:
                external: false
